name: "CD"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: "빌드 및 테스트"
    runs-on: ubuntu-latest
    steps:
      - name: "Repository 코드 불러오기"
        uses: actions/checkout@v5

      - name: "Gradle Wrapper 검증"
        uses: gradle/actions/wrapper-validation@v5

      - name: "자바21 설치"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: "빌드 권한 설정"
        run: chmod +x ./gradlew

      - name: "테스트 실행"
        run: ./gradlew test

      - name: "빌드 수행(JAR 생성)"
        run: ./gradlew build -x test

      - name: "빌드 파일 압축"
        run: |
          zip -r ./${{github.sha}}.zip \
            appspec.yml \
            scripts/ \
            build/libs/*.jar

      - name: "빌드 아티팩트 업로드"
        uses: actions/upload-artifact@v5
        with:
          name: build-artifact
          path: ./${{github.sha}}.zip
          retention-days: 1

  upload-to-s3:
    name: "S3 업로드"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "빌드 아티팩트 다운로드"
        uses: actions/download-artifact@v5
        with:
          name: build-artifact

      - name: "AWS 자격 증명"
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.ROLE_TO_ASSUME}}

      - name: "S3에 업로드"
        run: |
          aws s3 cp \
            --region ${{secrets.AWS_REGION}} \
            ./${{github.sha}}.zip \
            s3://${{secrets.AWS_S3_BUCKET}}/${{github.sha}}.zip

  deploy:
    name: "CodeDeploy 배포"
    runs-on: ubuntu-latest
    needs: upload-to-s3
    steps:
      - name: "AWS 자격 증명"
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.ROLE_TO_ASSUME}}

      - name: "CodeDeploy 배포"
        run: |
          aws deploy create-deployment \
            --application-name ${{secrets.AWS_CODE_DEPLOY_APPLICATION}} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{secrets.AWS_CODE_DEPLOY_GROUP}} \
            --s3-location bucket=${{secrets.AWS_S3_BUCKET}},key=${{github.sha}}.zip,bundleType=zip