name: "CD"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
  AWS_CODE_DEPLOY_APPLICATION: ${{secrets.AWS_CODE_DEPLOY_APPLICATION}}
  AWS_CODE_DEPLOY_GROUP: ${{secrets.AWS_CODE_DEPLOY_GROUP}}
  ROLE_TO_ASSUME: ${{secrets.ROLE_TO_ASSUME}}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: "CodeDeploy 배포"
    runs-on: ubuntu-latest
    steps:
      - name: "Repository 코드 불러오기"
        uses: actions/checkout@v5

      - name: "Gradle Wrapper 검증"
        uses: gradle/actions/wrapper-validation@v5

      - name: "자바21 설치"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: "빌드 권한 설정"
        run: chmod +x ./gradlew

      - name: "테스트 실행"
        run: ./gradlew test

      - name: "빌드 수행(JAR 생성)"
        run: ./gradlew build -x test

      - name: "빌드 파일 압축"
        run: zip -r ./${{github.sha}}.zip .

      - name: "AWS 자격 증명"
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::544409775039:role/wooteco-open-mission-githubactionsdeployrole

      - name: "S3에 업로드"
        run: |
          aws s3 cp \
            --region ${{ env.AWS_REGION }} \
            ./${{github.sha}}.zip \
            s3://${{ env.AWS_S3_BUCKET }}/${{github.sha}}.zip

      - name: "CodeDeploy 배포"
        run: aws deploy create-deployment \
          --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} \
          --s3-location bucket=${{env.AWS_S3_BUCKET}},key=${{github.sha}}.zip,bundleType=zip
