name: "CI"
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "feature/**"
      - "refactor/**"
      - "hotfix/**"

jobs:
  build-and-test:
    name: "테스트 및 JAR 파일 빌드"
    runs-on: ubuntu-latest
    steps:
      - name: "Repository 코드 불러오기"
        uses: actions/checkout@v5

      - name: "Gradle Wrapper 검증"
        uses: gradle/actions/wrapper-validation@v5

      - name: "자바21 설치"
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: "빌드 권한 설정"
        run: chmod +x ./gradlew

      - name: "테스트 실행"
        run: ./gradlew test

      - name: "빌드 수행(JAR 생성)"
        run: ./gradlew build -x test